
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka




server:
  port: 8070
spring:
  cloud:
    discovery:
      client:
        enabled: true
  application:
    name: schools


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schools
    username: root
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect


application:
  config:
    students-url: http://localhost:8090/api/v1/students


management:
  tracing:
    sampling:
      probability: 1.0